spring.application.name=kfokam48-epreuve-207
spring.datasource.url=jdbc:postgresql://localhost:5432/kfokam48_db
spring.datasource.username=kfokam_user
spring.datasource.password=kfokam_password
spring.datasource.driver-class-name=org.postgresql.Driver

# B5 : Schéma versionné par Flyway (interdit ddl-auto=update en prod)
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
