spring.application.name=kfokam48-epreuve-207
spring.datasource.url=jdbc:postgresql://localhost:5432/kfokam48_db
spring.datasource.username=kfokam_user
spring.datasource.password=kfokam_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
